### ISSUE TITLE
🚀 Open Links in EMails in a new window

### ISSUE THREAD

**Issue by ulfgebhardt** [cypht-org/cypht#317]
### Open Links in EMails in a new window

It would be nice if there were an option to open every link in an email in a new window by default.

Currently the links are opened in the same tab as cypht - which is no real problem, but if you forget to press ctrl now and lose your open Email client.

If I missed such an option please show me how to activate it.

Since i mostly view text messages it should be quite easy to add a `target="_blank"` - for html emails it might be more complex?! - especially when not every link is one which points outside the email, but a jumpmarker `#mymarker`.

**Comment by jasonmunro** [comment]
We actually used to do this for both text and html E-mail links, however I disabled it because of this:

https://www.owasp.org/index.php/Reverse_Tabnabbing

I know we can use noopener but I was concerned about browser support so I removed all target attributes.

**Comment by ulfgebhardt** [comment]
ok I get that - your choice to close this issue - i will live with the ctrl+click ;-)

**Comment by jasonmunro** [comment]
I feel we really should err on the side of caution here so I'm closing :)

**Comment by StevenMassaro** [comment]
@jasonmunro Would you consider reopening this? According to [your link](https://www.owasp.org/index.php/Reverse_Tabnabbing):

> Update 2023 - this is fixed in modern, evergreen, browsers

**Comment by marclaporte** [comment]
@Yannick243 Please investigate and advise.

**Comment by Yannick243** [comment]
After researching the potential Reverse_Tabnabbing vulnerability that could result from that, I noticed that support for `rel='noopener'` is now implicitly enabled in the majority of modern browsers (since at least 2020) for links using `target='_blank'` as indicated here [https://caniuse.com/mdn-html_elements_a_implicit_noopener](https://caniuse.com/mdn-html_elements_a_implicit_noopener) except InternetExplorer. 
Consequently, this vulnerability is no longer as critical as before. I would suggest reintroducing `target='_blank' rel='noopener'` for external links. If this approach is acceptable, I can submit a pull request.

**Comment by marclaporte** [comment]
@josaphatim @kroky @jasonmunro

**Comment by kroky** [comment]
I agree, target blank in conjunction with rel=noopener have pretty good support for quite some years in most browsers and it feels more natural to open email links in new tabs/windows.
