### ISSUE TITLE
Maybe we should have 2 forwarding actions, like Nextcloud Mail?

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#605]
<img width="337" alt="2022-08-24_091525" src="https://user-images.githubusercontent.com/1004261/186735524-a56ce970-03b5-4d4d-b149-7755b801f1a3.png">

One is forward the whole thing as one attachment, without any modifications. The other is forward by converting to text that I can modify before I send. I usually the later, but I know Jason prefers the former.

Related:
https://github.com/jasonmunro/cypht/pull/558
https://github.com/jasonmunro/cypht/issues/557

**Comment by dumblob** [comment]
This has been discussed before somewhere. I think the problem was which email part to choose (emails nowadays are heavily multipart and heavily nested) and conversions between mime types (this second issue is though solvable by giving the user two choices: 1. *plain copy & paste /i.e. keep the mime type and compose in that mime type/* 2. *smart heuristics*).

**Comment by dumblob** [comment]
Related:
https://github.com/jasonmunro/cypht/issues/12
https://github.com/jasonmunro/cypht/issues/382

**Comment by amaninyumu1** [comment]
https://github.com/cypht-org/cypht/pull/1080
![Forward](https://github.com/cypht-org/cypht/assets/51401043/a2f07eb1-445e-4031-8a30-91d2c266294a)

**Comment by marclaporte** [comment]
Work in progress: https://github.com/cypht-org/cypht/pull/1080
