### ISSUE TITLE
Analyze recommendations from useplaintext.email and get listed

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#837]
https://useplaintext.email/#implementation-recommendations

@jasonmunro @dumblob

**Comment by jasonmunro** [comment]
Cypht appropriately sends text aliternative when using HTML for outbound mail, however I just noticed a bug was introduced in that process that is causing the text version to have a bunch of html entities in it. I will post another issue with the fix for that.

Markdown is converted to HTML on send, and a text copy of that should be included in the message but I have not tested that path yet.

**Comment by jasonmunro** [comment]
https://github.com/cypht-org/cypht/issues/850

**Comment by Shadow243** [comment]
PR: https://github.com/cypht-org/cypht/pull/851

**Comment by marclaporte** [comment]
Still need to get listed at https://useplaintext.email/#recommended-clients

**Comment by Shadow243** [comment]
A patchset has already been sent, we are waiting for the feedback.

[https://git.sr.ht/~shadow243/useplaintext.email.git/commit/20db6d812376a3ebee93140c0f564f79e5c94180](https://git.sr.ht/~shadow243/useplaintext.email.git/commit/20db6d812376a3ebee93140c0f564f79e5c94180)

**Comment by marclaporte** [comment]
It was merged in: https://git.sr.ht/~sircmpwn/useplaintext.email/commit/0e2bdd0762b9a1427c84c7b3382c8dedba1f9209

And Cypht is present here: https://useplaintext.email/#recommended-clients
